### ISSUE TITLE
Custom refresh rates

### ISSUE THREAD

**Issue by Keith94** [GMMan/AsteTweak#2]
Astebreed forces a refresh rate of 60 Hz for all resolutions. One issue for users with high refresh rate monitors, is that it takes longer to start/quit/Alt+Tab the game if the refresh rates are constantly switching. 
Is it possible for AsteTweak to set a custom refresh rate as well?

**Comment by GMMan** [comment]
IIRC the game speed is tied to the framerate, so if you raise it, it's going to go way too fast. I'll check again.

**Comment by Keith94** [comment]
I know, it's possible to limit the *frame* rate so it doesn't mess with the game speed. I was just asking if it was possible for you to change the full screen *refresh* rate within the exe or something like that.

**Comment by GMMan** [comment]
Interesting distinction, I'll check on that.

**Comment by GMMan** [comment]
I've managed to find the part that determines which refresh rate to use. Which version of the game do you have? I want to send a binary patch to test whether this works before implementing anything.

**Comment by Keith94** [comment]
I'm using the GOG.com v3.00 (Definitive Edition). I'd be happy to test whatever you got. :)

**Comment by GMMan** [comment]
What refresh rate are you targeting?

**Comment by Keith94** [comment]
I'm targeting 120 Hz. My display supports 60, 100, and 120 Hz refresh rates.

**Comment by GMMan** [comment]
[Here](https://www.dropbox.com/s/woxt7wp934v4g01/gog_120hz.patch?dl=1)'s a 120 Hz patch. You can get BSPatch [here](https://www.pokorra.de/coding/bsdiff.html).

**Comment by Keith94** [comment]
Okay, I put bsdiff.exe, bspatch.exe, and gog_120hz.patch in the game folder and double-clicked bspatch.exe. The game still launches at 60 Hz. Did I do something wrong?

**Comment by GMMan** [comment]
You need to tell BSPatch to patch the file with command line args. Something like `bspatch.exe Astebreed.exe Astebreed.exe gog_120hz.patch`.

**Comment by Keith94** [comment]
I knew I did something wrong. ;) Indeed, the patch does work correctly and the game runs at 120 Hz now.
